server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /demographic
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: lyh
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.128:3306/db_demographic?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd
  #上传文件大小设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ygjy.entity

#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

#上传路径
file:
  staticAccessPath: /upload/**
  uploadFolder: E:/upload/